### PR TITLE
make the package cross-compile safe

### PR DESCRIPTION
**Pull request by LocutusOfBorg**

### CODE REVIEW

**Comment by q4z1** [comment]
Hi LocutusOfBorg,

thx a lot for your contribution.

Can you provide this pull request for stable branch?

Master branch isn't used anymore at the moment.

Kind regards.

**Comment by LocutusOfBorg** [comment]
done!

**Comment by q4z1** [comment]
Thx a lot 8-)

**Comment by LocutusOfBorg** [comment]
thanks to you! I hope to see soon a new release with all the pending fixes :)

**Pull request merged**
