### PR TITLE
GitHub actions builder

### PR DESCRIPTION
**Pull request by bynsr**
Downloads dependencies and builds for Linux on GitHub Actions.
The build isn't successful at the moment, it does need some current PokerTH build gurus to sort out the dependencies.

The builds logs will be visible at https://github.com/pokerth/pokerth/actions

### CODE REVIEW

**Comment by q4z1** [comment]
You can simplify by `apt build-dep pokerth` - and then just install missing mysql++-dev.
(uncomment sources in /etc/apt)

Tested on Debian Buster and Ubuntu 18.04

**Comment by bynsr** [comment]
Thanks!
Do you have the qmake args needed? (it's using Ubuntu 18.04) on GHA)

`qmake QMAKE_CFLAGS_ISYSTEM= -spec linux-g++ CONFIG+=client pokerth.pro`
results in `qmake: could not find a Qt installation of ''`

Same if I skip the `QMAKE_CFLAGS_ISYSTEM`

**Comment by albmed** [comment]
Try with opening and ending double quotes: 
`qmake QMAKE_CFLAGS_ISYSTEM="" CONFIG+="client" -spec linux-g++ pokerth.pro`

**Comment by bynsr** [comment]
Getting there. 
Using full path to qmake seems to work, but build fails with another error. 
qmake command: `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake QMAKE_CFLAGS_ISYSTEM= -spec linux-g++ CONFIG+=client pokerth.pro`

Build log is here: https://github.com/bynsr/pokerth/commit/3e67973d38ec9379de9a2d6ebacf1b7d77559dd1/checks/772388794/logs 

Any ideas?

**Comment by bynsr** [comment]
Realized you might not be able to view the build logs. 
The latest runs can be seen here: https://github.com/bynsr/pokerth/actions/runs/135926038

The current build seems to be a valid error in the code, so I think this could be merged into master to get fresh master builds going on Github Actions? 

I've added a support for building automatically on a mac too, but it needs to install the dependencies. Any helpers? 

```
2020-06-15T12:00:43.8768272Z g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DENABLE_IPV6 -DTIXML_USE_STL -DBOOST_FILESYSTEM_DEPRECATED -DPREFIX="/usr" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -Isrc/third_party/qtsingleapplication -Isrc/third_party/qtlockedfile -I. -Isrc -Isrc/engine -Isrc/gui -Isrc/net -Isrc/engine/local_engine -Isrc/engine/network_engine -Isrc/config -Isrc/gui/qt -Isrc/gui/qt/connecttoserverdialog -Isrc/core -Isrc/gui/qt/sound -Isrc/gui/qt/qttools -Isrc/gui/qt/chattools -Isrc/gui/qt/qttools/qthelper -Isrc/gui/qt/gametable -Isrc/gui/qt/gametable/startsplash -Isrc/gui/qt/gametable/log -Isrc/gui/qt/aboutpokerth -Isrc/gui/qt/createnetworkgamedialog -Isrc/gui/qt/createinternetgamedialog -Isrc/gui/qt/joinnetworkgamedialog -Isrc/gui/qt/newlocalgamedialog -Isrc/gui/qt/settingsdialog -Isrc/gui/qt/settingsdialog/selectavatardialog -Isrc/gui/qt/settingsdialog/manualblindsorderdialog -Isrc/gui/qt/startnetworkgamedialog -Isrc/gui/qt/startwindow -Isrc/gui/qt/serverlistdialog -Isrc/gui/qt/styles -Isrc/gui/qt/changecontentdialog -Isrc/gui/qt/changecompleteblindsdialog -Isrc/gui/qt/internetgamelogindialog -Isrc/gui/qt/mymessagedialog -Isrc/gui/qt/gamelobbydialog -Isrc/gui/qt/timeoutmsgbox -Isrc/gui/qt/logfiledialog -Isrc/gui/qt/mymessagebox -I/usr/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Imocs -I/usr/include/libdrm -Iuics -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o obj/mysetlabel.o src/gui/qt/gametable/mysetlabel.cpp
2020-06-15T12:00:45.0452639Z src/gui/qt/gametable/gametableimpl.cpp: In member function ‘void gameTableImpl::triggerVoteOnKick(int)’:
2020-06-15T12:00:45.0453288Z src/gui/qt/gametable/gametableimpl.cpp:3849:19: error: call of overloaded ‘advance(PlayerListIterator&, int&)’ is ambiguous
2020-06-15T12:00:45.0453532Z     advance(pos, id);
2020-06-15T12:00:45.0453661Z                    ^
2020-06-15T12:00:45.0456651Z In file included from /usr/include/c++/7/bits/stl_algobase.h:66:0,
2020-06-15T12:00:45.0456794Z                  from /usr/include/c++/7/algorithm:61,
2020-06-15T12:00:45.0457207Z                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:109,
2020-06-15T12:00:45.0457481Z                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/qatomic.h:41,
2020-06-15T12:00:45.0457834Z                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:43,
2020-06-15T12:00:45.0458104Z                  from /usr/include/x86_64-linux-gnu/qt5/QtCore/QVariant:1,
2020-06-15T12:00:45.0458227Z                  from uics/ui_gametable.h:12,
2020-06-15T12:00:45.0458340Z                  from src/gui/qt/gametable/gametableimpl.h:38,
2020-06-15T12:00:45.0458452Z                  from src/gui/qt/gametable/gametableimpl.cpp:31:
2020-06-15T12:00:45.0458751Z /usr/include/c++/7/bits/stl_iterator_base_funcs.h:197:5: note: candidate: void std::advance(_InputIterator&, _Distance) [with _InputIterator = std::_List_iterator<boost::shared_ptr<PlayerInterface> >; _Distance = int]
2020-06-15T12:00:45.0458906Z      advance(_InputIterator& __i, _Distance __n)
2020-06-15T12:00:45.0459016Z      ^~~~~~~```

**Comment by bynsr** [comment]
Status:
The script/setup now tries to build both on Linux and Mac.  It fails on Linux due to error in PokerTH code and fails on macOS due to dependencies.

I think I've done what I can to get this going, would be good if some of the devs could sort out the remaining macos dependencies. 

Having GHA running automatically will mean the project will be in more of a known state.

**Comment by andy5995** [comment]
@bynsr  did a lot of work on this and it seems very thorough. At this point, what might be best in the long-term is to merge this as-is, and then tweak it from there, update dependencies as needed/desired. I think it'll be easier to work with once the Action is running (even if it's failing atm) on the pokerth repo.

**Pull request closed without merging**
